[tool.ruff]
target-version = "py310"
line-length = 100
extend-exclude = ["alembic/versions", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "PIE", "C4", "SIM", "PTH"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["app"]

# Игноры по файлам/папкам для типичных паттернов FastAPI/Alembic
[tool.ruff.lint.per-file-ignores]
"alembic/env.py" = ["E402", "PTH118", "PTH120"]
"app/routes/__init__.py" = ["F401"]
"app/routes/*.py" = ["B008"]
"app/dependencies/*.py" = ["B008"]
"app/core/security.py" = ["B008"]

[tool.mypy]
python_version = "3.10"
packages = ["app"]
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
exclude = "(alembic/|tests/)"
